name: Benchmark

on:
  workflow_call:

env:
  NODE_VERSION: '16'

jobs:

  benchmark:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: terminusdb-server-docker-image

      - name: Run server
        run: |
          docker load < terminusdb-server-docker-image.tar.gz
          docker run \
            --detach \
            --net=host \
            terminusdb/terminusdb-server:local

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v2

      - name: Run benchmarks
        working-directory: tests
        run: |
          npm ci
          npm run bench

