name: Build

on:
  workflow_call:

jobs:

  build:
    name: Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: terminusdb/terminusdb-server:local
          outputs: type=docker,dest=terminusdb-server-docker-image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: TERMINUSDB_GIT_HASH=${{ github.sha }}

      - name: Compress image
        run: gzip terminusdb-server-docker-image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v2
        with:
            name: terminusdb-server-docker-image
            path: terminusdb-server-docker-image.tar.gz
