name: CI

on:
  push:
    branches:
    tags:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - LICENSE

# Prevent redundant workflows triggered by push and pull_request events.
concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: true

env:
  NODE_VERSION: '16'

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml

  benchmark:
    name: Benchmark
    needs: build
    uses: ./.github/workflows/benchmark.yml

  # This is required for status checks.
  all_checks_pass:
    name: All checks pass
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Celebrate! 🥳"

  push:
    name: Deploy
    runs-on: ubuntu-latest
    needs: all_checks_pass
    if: |
      github.repository == 'terminusdb/terminusdb' &&
      github.event_name == 'push' && (
        github.ref == 'refs/heads/main' ||
        startsWith(github.ref, 'refs/tags/v')
      )

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: terminusdb-server-docker-image

      - name: Push image to Docker Container Registry
        run: |
          echo '${{ secrets.DOCKER_PASS }}' | docker login -u terminusdb --password-stdin

          # Strip git ref prefix from version
          VERSION=$(echo "$GITHUB_REF" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `dev` tag convention for main branch
          [ "$VERSION" == "main" ] && VERSION=dev

          docker load < terminusdb-server-docker-image.tar.gz

          # Image identifiers
          LOCAL_IMAGE=terminusdb/terminusdb-server:local
          VERSION_IMAGE=terminusdb/terminusdb-server:$VERSION
          DEV_COMMIT_IMAGE=terminusdb/terminusdb-server:$VERSION-$GITHUB_SHA
          LATEST_IMAGE=terminusdb/terminusdb-server:latest

          # Tag and push the version image
          docker tag $LOCAL_IMAGE $VERSION_IMAGE
          docker push $VERSION_IMAGE

          # Tag and push the dev-commit image. This is removed later.
          if [ "$VERSION" == "dev" ]; then
            docker tag $LOCAL_IMAGE $DEV_COMMIT_IMAGE
            docker push $DEV_COMMIT_IMAGE
          fi

          # Tag and push the latest image when a version tag is pushed
          if [ $(echo "$GITHUB_REF" | grep "refs/tags/v") ]; then
             docker tag $LOCAL_IMAGE $LATEST_IMAGE
             docker push $LATEST_IMAGE
          fi

  enterprise:
    name: Trigger enterprise build
    runs-on: ubuntu-latest
    needs: push
    if: |
      github.repository == 'terminusdb/terminusdb' &&
      github.event_name == 'push' && (
        github.ref == 'refs/heads/main'
      )

    steps:
      - name: Deploy Stage
        run: |
          curl -X POST https://api.github.com/repos/${{ secrets.ENTERPRISE_REPO_OWNER }}/${{ secrets.ENTERPRISE_REPO }}/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u rrooij:${{ secrets.PAT }} -d '{ "event_type": "Trigger from community" }'

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: push
    if: |
      github.repository == 'terminusdb/terminusdb' &&
      github.event_name == 'push' && (
        startsWith(github.ref, 'refs/tags/v')
      )

    steps:
    - uses: actions/checkout@v2

    - name: Set release name
      id: release_name
      run: |
        TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        TAG_WITH_SUFFIX="$TAG"
        echo "::set-output name=tag::$TAG_WITH_SUFFIX"

    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_name.outputs.tag }}
      continue-on-error: true

    - name: Create a release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_name.outputs.tag }}
        prerelease: ${{ !contains(github.ref, 'tags') }}
