name: Docs

on:
  push:
    paths:
      - '**.md'
      - 'docs/**'
      - LICENSE
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'
      - LICENSE

jobs:

  # This is required for status checks. Since we don't have anything to check in
  # the above paths, we do nothing.
  all_checks_pass:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to be done. 😌"
