name: Docs

on:
  push:
    paths:
      - '**.md'
      - 'docs/**'
      - LICENSE
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'
      - LICENSE

# Prevent redundant workflows triggered by push and pull_request events.
concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # This is required for status checks.
  all_checks_pass:
    name: All checks pass
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to be checked! 😌"
