name: PR

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - LICENSE

# Prevent redundant workflows triggered by push and pull_request events.
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ci:
    uses: spl/terminusdb/.github/workflows/ci.yml@mymain
