name: PR

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - LICENSE

# Prevent redundant workflows triggered by push and pull_request events.
concurrency:
  group: ci-${{ github.event.pull_request.head.sha }}
  cancel-in-progress: true

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yml

  check:
    name: Check
    needs: build
    uses: ./.github/workflows/check.yml

  benchmark:
    name: Benchmark
    needs: build
    uses: ./.github/workflows/benchmark.yml

  # This is required for status checks.
  all_checks_pass:
    name: All checks pass
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: echo "Celebrate! 🥳"
