name: PR

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - LICENSE

# Prevent redundant workflows triggered by push and pull_request events.
concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  ref:
    name: Print ref
    runs-on: ubuntu-latest
    steps:
      - run: echo "gitub.ref=${{ github.ref }}"
      - run: echo "gitub.head_ref=${{ github.head_ref }}"
      - run: echo "gitub.repository=${{ github.repository }}"

  build:
    name: Build
    uses: ./.github/workflows/build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml

  benchmark:
    name: Benchmark
    needs: build
    uses: ./.github/workflows/benchmark.yml

  # This is required for status checks.
  all_checks_pass:
    name: All checks pass
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Celebrate! 🥳"
