# Build `terminusdb` and run the unit tests.
name: Test

on:
  push:
  pull_request:

jobs:

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Installing swipl on Debian: https://www.swi-prolog.org/build/PPA.html
          sudo apt-add-repository ppa:swi-prolog/stable
          sudo apt-get update
          sudo apt-get install swi-prolog

      - name: Install terminus_store_prolog
        run: swipl -g "pack_install(terminus_store_prolog, [interactive(false), upgrade(true)])"

      - name: Build
        run: make

      - name: Run tests
        run: ./terminusdb test

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Installing swipl on macOS: https://www.swi-prolog.org/build/macos.html
          brew install swi-prolog

      - name: Install terminus_store_prolog
        run: swipl -g "pack_install(terminus_store_prolog, [interactive(false), upgrade(true)])"

      - name: Build
        run: make

      - name: Run tests
        run: ./terminusdb test

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM and SWI Prolog
        run: |
          # Install the latest stable LLVM and SWI Prolog using Chocolatey.
          choco install llvm swi-prolog --no-progress
          # Abort early since it doesn't seem that failure causes an exit here.
          if ($lastExitCode -ne 0) { throw "choco install failed: $lastExitCode" }

          # Update the $PATH to include the new packages. See
          # <https://stackoverflow.com/a/46760714>
          Import-Module "$env:ProgramData\chocolatey\helpers\chocolateyInstaller.psm1"
          Update-SessionEnvironment

          # Display versions for debugging
          swipl --version
          clang --version

          # The following commands update GitHub files to make the environment
          # variables persistent across steps. See
          # <https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions>

          # Append the `swipl` path to the $PATH.
          echo (Split-Path -Path (Get-Command swipl).Source) `
            | Out-File -Encoding utf8 -Append -FilePath $env:GITHUB_PATH

          # Set $LIBCLANG_PATH with the `clang` path.
          echo "LIBCLANG_PATH=$(Split-Path -Path (Get-Command clang).Source)" `
            | Out-File -Encoding utf8 -Append -FilePath $env:GITHUB_ENV

      - name: Install terminus_store_prolog
        run: swipl -g "pack_install(terminus_store_prolog, [interactive(false), upgrade(true)])"

      - name: Build
        # Use Git Bash because the Makefile does not work in other shells.
        shell: bash
        run: make

      - name: Run tests
        run: .\terminusdb test
